name: Main
on: push
jobs:
    code-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install deps
              run: npm ci
            - name: Eslint
              run: npm run lint
            - name: Prettier
              run: npm run prettier:check
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install deps
              run: npm ci
            # - name: Test
            #   run: npm run test
